name: Deploy documents to the server
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master

      # 解决子模块所有权问题
      - name: Set safe directory
        run: git config --global --add safe.directory $(pwd)
    
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive

      # 使用 node:20
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20

      # 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 使用 pnpm 安装 Docusaurus 依赖
      - name: Install Docusaurus dependencies
        run: pnpm install

      # 清理 Docusaurus 构建目录
      - name: Docusaurus clear
        run: pnpm docusaurus clear

      # 构建项目
      - name: Docusaurus build
        run: pnpm docusaurus build

      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "build/"  # Docusaurus 默认构建输出目录
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
